// User Actions
export const USER_LOG_IN_PENDING = 'USER_LOG_IN_PENDING';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_ERROR = 'USER_LOG_IN_ERROR';
export const USER_LOG_OUT = 'USER_LOG_OUT';

// App Management
export const APP_MODAL_ERROR = 'APP_MODAL_ERROR';
export const APP_CLEAR_ERRORS = 'APP_CLEAR_ERRORS';
export const APP_ENABLE_EDITING = 'APP_ENABLE_EDITING';
export const APP_DISABLE_EDITING = 'APP_DISABLE_EDITING';

// Universe Actions
export const UNIVERSES_FETCH_PENDING = 'UNIVERSES_FETCH_PENDING';
export const UNIVERSES_FETCH_SUCCESS = 'UNIVERSES_FETCH_SUCCESS';
export const UNIVERSES_FETCH_ERROR = 'UNIVERSES_FETCH_ERROR';
export const UNIVERSES_FETCH_ONE_PENDING = 'UNIVERSES_FETCH_ONE_PENDING';
export const UNIVERSES_FETCH_ONE_SUCCESS = 'UNIVERSES_FETCH_ONE_SUCCESS';
export const UNIVERSES_FETCH_ONE_ERROR = 'UNIVERSES_FETCH_ONE_ERROR';
export const UNIVERSES_ADD_ONE = 'UNIVERSES_ADD_ONE';

// Character Actions
export const CHARACTERS_FETCH_PENDING = 'CHARACTERS_FETCH_PENDING';
export const CHARACTERS_FETCH_SUCCESS = 'CHARACTERS_FETCH_SUCCESS';
export const CHARACTERS_FETCH_ERROR = 'CHARACTERS_FETCH_ERROR';
export const CHARACTERS_FETCH_ONE_PENDING = 'CHARACTERS_FETCH_ONE_PENDING';
export const CHARACTERS_FETCH_ONE_SUCCESS = 'CHARACTERS_FETCH_ONE_SUCCESS';
export const CHARACTERS_FETCH_ONE_ERROR = 'CHARACTERS_FETCH_ONE_ERROR';
export const CHARACTERS_ADD_ONE = 'CHARACTERS_ADD_ONE';
export const CHARACTERS_UPDATE_ONE = 'CHARACTERS_UPDATE_ONE';
