// User Actions
export const USER_LOG_IN_PENDING = 'USER_LOG_IN_PENDING';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_ERROR = 'USER_LOG_IN_ERROR';
export const USER_LOG_OUT = 'USER_LOG_OUT';

// App Management
export const APP_MODAL_ERROR = 'APP_MODAL_ERROR';

// Universe Actions
export const UNIVERSES_FETCH_PENDING = 'UNIVERSES_FETCH_PENDING';
export const UNIVERSES_FETCH_SUCCESS = 'UNIVERSES_FETCH_SUCCESS';
export const UNIVERSES_FETCH_ERROR = 'UNIVERSES_FETCH_ERROR';
export const UNIVERSES_SELECT_ONE = 'UNIVERSES_SELECT_ONE';
export const UNIVERSES_CLEAR_SELECTED = 'UNIVERSES_CLEAR_SELECTED';
export const UNIVERSES_ADD_ONE = 'UNIVERSES_ADD_ONE';

// Character Actions
export const CHARACTERS_FETCH_PENDING = 'CHARACTERS_FETCH_PENDING';
export const CHARACTERS_FETCH_SUCCESS = 'CHARACTERS_FETCH_SUCCESS';
export const CHARACTERS_FETCH_ERROR = 'CHARACTERS_FETCH_ERROR';
export const CHARACTERS_SELECT_ONE = 'CHARACTERS_SELECT_ONE';
export const CHARACTERS_CLEAR_SELECTED = 'CHARACTERS_CLEAR_SELECTED';
export const CHARACTERS_ADD_ONE = 'CHARACTERS_ADD_ONE';
