name: Develop

on:
  push:
    branches:
    - develop

jobs:
  build:
    name: Check Tellit builds successfully
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: builds
      run: |
        npm install
        npm run build --if-present
        
  tests:
    name: Check unit tests pass
    needs: build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: run unit tests
      run: |
        npm install
        npm test -- --watchAll=false
        
