name: Master

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Check Tellit builds successfully
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: |
        npm install
    - name: run build
      run: |
        npm run build --if-present
        
  tests:
    name: Check unit tests pass
    needs: build
    runs-on: ubuntu-latest  
    timeout-minutes: 3  
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: |
        npm install
    - name: run unit tests
      run: |
        npm test -- --watchAll=false

  # deploy:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: git Actions
  #       uses: srt32/git-actions@v0.0.3
  #     - name: deploy to Github Pages
  #       run: |
  #         git ... 
